# This workflow will build a .NET project

name: Compilation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Change directory
      run: cd API
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /warnaserror
  
  test:
    runs-on: ubuntu-latest
    env:
      GALLIUM_ENV: test
      GALLIUM_HTTP: 5080
      GALLIUM_HTTPS: 5443
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Change directory
      run: cd API
    - name: Restore dependencies
      run: dotnet restore
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 12.x
    - name: Install newman
      run: npm install -g newman
    - name: Run tests
      uses: BerniWittmann/background-server-action@v1.1.0
      with:
        command: newman postman/collections/Collection.json -e postman/test.env.json -k
        build: dotnet build --no-restore API
        start: dotnet run --no-build --project API
        wait-on: http://localhost:5080/api/products
        wait-on-timeout: 20


      


    
